### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by shreevatsa** [sanskrit-coders/chandas#1]
I think there's enough overlap with [other repo](https://github.com/shreevatsa/sanskrit) for this to count as "derivative" (e.g. [this](https://github.com/sanskrit-coders/chandas/blob/6eb09dd/chandas/identify/pattern.py) and [this](https://github.com/sanskrit-coders/chandas/blob/06c6b30/chandas/metrical_data/__init__.py)); could you change licence to copyleft ([GPLv2 or later](https://github.com/shreevatsa/sanskrit/blob/master/LICENSE))? Would make me more willing to contribute too :)

**Comment by vvasuki** [comment]
Done

**Comment by shreevatsa** [comment]
(We had an offline conversation…) Feel free to re-license under MIT / Apache / BSD / whatever.
